# Delayed::Worker.logger = Rails.logger
Delayed::Worker.logger = Logger.new(Rails.root.join('log', 'dj.log'))
Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 3
Delayed::Worker.max_run_time = 1.hour
Delayed::Worker.default_priority = 10
Delayed::Worker.read_ahead = 10
Delayed::Worker.delay_jobs = !Rails.env.test?
Delayed::Worker.raise_signal_exceptions = :term
